### ISSUE TITLE
CCB: Multiple addresses marked "Home"

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Slingshot#13]
The CCB import code already knows about an address type of Mailing, but CCB's UI also defines Home, Work, and Other.

Rock only has Home, Work, and Previous location types. 

I think Mailing should probably be created as a new Location Type, as it doesn't fit into any of those other categories.

**Comment by edmistj** [comment]
I'm thinking the type 'Mailing' should be = Home + IsMailing in Rock. 

Work makes sense bring over and I guess 'Other' should be added by the import (though that could take a bit to add).

**Comment by edmistj** [comment]
@dcs619 I'm not sure I understand your last comment.

**Comment by dcs619** [comment]
@edmistj As an example, addresses in CCB:
Jon:
Home: 1 North Main
Mailing: 43 Candle Street
David:
Home: 1 South Main

Addresses in Rock with current import code:
Jon:
Home + IsMailing: 1 North Main
Home + IsMailing: 43 Candle Street
David:
Home + IsMailing: 1 South Main

Addresses in Rock with new import code:
Jon:
Home: 1 North Main
Home + IsMailing: 43 Candle Street
David:
Home: 1 South Main

That's simplified, but wanted to make sure that wouldn't create issues where a `Home` address is no longer marked `IsMailing`.

**Comment by edmistj** [comment]
@dcs619 that sounds good.
