### ISSUE TITLE
CCB: All groups imported as Active when some are Inactive

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Slingshot#15]
The CCB API returns an `<inactive>` tag that should be checked to decide the Rock Group.IsActive status.

http://designccb.s3.amazonaws.com/helpdesk/files/official_docs/api.html

**Comment by mkinyon** [comment]
This is something that other Churches have been asking for with data migrations.  I can see this getting added to the other Slingshot exporters as well.
