### ISSUE TITLE
CCB: update person image export behavior

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Slingshot#25]
I see code on the Rock side that looks for `*.images.slingshot` but I don't get that file in the local directory when I run against CCB.  

During the person export from the API an HMAC-signed AWS url is generated and attached to `Slingshot.Core.Person.PhotoUrl`.  It seems the only missing step is to download that photo into the ImportPackage.ImageDirectory.

**Comment by mkinyon** [comment]
As you noticed, the CCB Slingshot tool will only export the photo URLs as part of the person export. To import the photos, all you need to do is click the Import Photos button in Rock and Slingshot will download the photos from AWS.  Keep in mind that the urls have an expiration date so you don’t want to wait to long after exporting. 

There are other systems such as F1 that don’t support image URLs so instead the photos are downloaded and saved to a *.Images.Slingshot file.

**Comment by dcs619** [comment]
👍 I found that late yesterday and forgot to update this issue.  Considering the HMAC signature expiration I think it'd be better for CCB to export the image immediately.  

Benefits of immediately downloading the image:
1) Consistency with F1 export
2) Reuse slingshot files for dev/test servers
3) Easy to spot-check for missing files

Cons of delayed image download
1) Bandwidth limitations?

@edmistj any thoughts?

**Comment by mkinyon** [comment]
Just my two cents. I like the idea of downloading the images immediately.

**Comment by edmistj** [comment]
We'd be fine with a PR for that. We didn't have the concept of the download when the CCB was originally written. We added that feature to support the F1 import.

**Comment by dcs619** [comment]
Ok, I'll start on a PR with those changes.  I'll separate it from the [CCB Groups update](https://github.com/SparkDevNetwork/Slingshot/pull/24) unless you want me to include it there.

**Comment by edmistj** [comment]
Probably should be separate.
