### ISSUE TITLE
CCB: API Rate Limiting

### ISSUE THREAD

**Issue by danielmilner** [SparkDevNetwork/Slingshot#26]
Church Community Builder will begin rate limiting their API starting on July 30th, 2018.

https://www.churchcommunitybuilder.com/software-news/api-rate-limiting

**Comment by dcs619** [comment]
This rate limit doesn't seem overly restrictive unless they also enforce "requests for larger amounts of data" and they consider 500 a large amount.  

Initial discovery of what the rate limit would affect:
- 1 call per API login
- 1 call per API uptime
- 1 call per all GroupTypes
- 1 call per all Departments
- 1 call per all Accounts
- 1 call per page of Groups (default 500)
- 1 call per page of Events (default 500)
- 1 call per month of Attendance (includes event)
- 1 call per month of Batches (includes transactions)
- 1 call per month of Attendance (matches events)

If my math is correct, then an average sized client requesting the last 5 years of data would make 192 API calls.  10 years of data would be 372 API calls.

**Comment by danielmilner** [comment]
May just need to add checking and verification that something else hasn't already exhausted the rate limit.

**Comment by dcs619** [comment]
The deadline has been updated to [August 20th](https://www.churchcommunitybuilder.com/software-news/api-rate-limiting)

**Comment by dcs619** [comment]
@danielmilner have you started updating any of the codebase?

**Comment by danielmilner** [comment]
@dcs619 No, I'm not a C# developer...but I am familiar with the Church Community Builder API.

**Comment by dcs619** [comment]
This issue can be closed
