### ISSUE TITLE
F1: Adding MDF map to complement the API map

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Slingshot#4]
Over the next few weeks/months I plan on adding full support for an F1 MDF conversion to Slingshot.  I haven't checked to see if Slingshot supports every Rock EntityType but will ask for clarification if I need it.

I'd like to also propose a pattern for Unit Tests on Slingshot methods so that future Rock updates will highlight any breaking schema changes.  This may take me longer to finish than the initial mapping process, but wanted to highlight it here for awareness.

**Comment by edmistj** [comment]
Sounds good.

**Comment by jagibb** [comment]
Any updates on this progress, @dcs619? We are desiring an MDF map as well.

**Comment by dcs619** [comment]
It's in progress and due for release in the next 3 weeks.

**Comment by jagibb** [comment]
Hey @dcs619, how is progress coming along with this build? Are you building out support on both Rock side and client side for Requirement Documents?

**Comment by dcs619** [comment]
@jagibb Missed this notification.  All requirements, check images and ministry documents are exported separately from the MDF and MDF is the only scope I'm tackling right now.

Slingshot already supports file imports so those files would need to be named appropriately then could be imported into Rock as is.

**Comment by JoshuaMaiorino** [comment]
@dcs619 Any update on progress on this?

**Comment by dcs619** [comment]
@JoshuaMaiorino files are on my fork but I need to open a WIP PR with what's left to be done

**Comment by JoshuaMaiorino** [comment]
@dcs619 I'm happy to help work on it.  It's something we'd really like to see, as the API is very limited.

**Comment by dcs619** [comment]
Added WIP PR #35

**Comment by JoshuaMaiorino** [comment]
This could probably be closed at this point. @jonedmiston

**Comment by jonedmiston** [comment]
Thanks!
