### ISSUE TITLE
Import Process

### ISSUE THREAD

**Issue by feldeiry** [SparkDevNetwork/Slingshot#59]
Hi,  It's not clear in any of your documentation how to install and use Slingshot on Rock itself.  Everything points to the export process and how to make the .slingshot file.  Now, what do you do with that?  I only saw a hint that it should be under Power Tools > Legacy Import, but I don't see that available.  Using Rock 10.3.

Thank you.

**Comment by jonedmiston** [comment]
To import a Slingshot file you'll need to create a new page in your Rock instance and add the 'Bulk Import' block to it.

**Comment by feldeiry** [comment]
Thanks.  Found it!
