### ISSUE TITLE
PCO: Marital Status does not export

### ISSUE THREAD

**Issue by guymaness2** [SparkDevNetwork/Slingshot#74]
Marital Status does not export. All records come out with marital status set to "Unknown". Upon examining the code, there is a typo in one of the options of the api request for individuals. "...,**martial**_status..." should be "...,**marital**_status..." in the line referenced below.

https://github.com/SparkDevNetwork/Slingshot/blob/8f590afab01714299397485a93d81b023e54ea15/Slingshot.PCO/Utilities/PCOApi/PCOApi.Individuals.cs#L57

I have verified that fixing the typo causes the export to properly extract the Marital Status value in a local fork of this code.

**Comment by abpena1979** [comment]
Fixed via https://github.com/SparkDevNetwork/Slingshot/commit/9e40764c1c44ee16790b50eea12ffda2bc1c8a14
