### ISSUE TITLE
Set REST security config to TLS 1.2

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Slingshot#8]
CCB has started enforcing TLS 1.2 (or higher) for all API/web requests and I would expect other providers to follow suit.  The default configuration for .NET 4.5 and RestRequest is SSL3 / TLS 1.0.

If you try to login with the default RestRequest configuration it will return HTTP status code 0 and Slingshot says "Unable to login with the information provided." 

[The fix](https://stackoverflow.com/a/28333370) is to force the SecurityProtocol to TLS 1.2.  I'm not sure if this could be done at the app level, or needs to be configured on a slingshot-by-slingshot basis.  Once this is done all API requests complete successfully.

**Comment by edmistj** [comment]
Thanks David! Is there a PR you could submit?

**Comment by dcs619** [comment]
Yes I'm planning to submit a PR for this and some other issues with the CCB import.  Do you have a preference which class/method I put that method in?  I was hoping to add it to `Slingshot.Core` so it would apply to all API imports, but I think it'll have to go in each import.

**Comment by edmistj** [comment]
Yeah it might need to be in each import app.

**Comment by dcs619** [comment]
Fixed in #12
